### ISSUE TITLE
Issues with --require and mocha@4 support

### ISSUE THREAD

**Issue by vlaad360** [yandex/mocha-parallel-tests#133]
**package.json**
`"test:coverage": "DEBUG_PORT=9998 NODE_ENV=test nyc mocha --opts './mocha.opts'"`

**mocha.opts**
```bash
--require src/js/testHelper.js
--require jsdom-global/register
--require chai/register-expect
--exit
./src/ts/Specs/**/*.spec.ts
```

Try 1:
```
Error: Cannot find module 'jsdom-global/register'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at exports.default (/usr/local/lib/node_modules/mocha-parallel-tests/dist/lib/utils/process-require-option.js:16:9)
    at binHelper (/usr/local/lib/node_modules/mocha-parallel-tests/dist/bin-helper.js:79:40)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha-parallel-tests/dist/bin/mocha-parallel-tests:37:25)
    at Module._compile (module.js:649:30)
    at Module.replacementCompile (/Users/v.yandimirkin/Projects/Anti-AdBlock/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/v.yandimirkin/Projects/Anti-AdBlock/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
```

jsdom-global is in dependencies
and without nyc it doesn't work either

**Comment by 1999** [comment]
Hi @vlaad360, thank you for posting the issue. What `mocha` version are you using?

**Comment by vlaad360** [comment]
@1999 
mocha "4.1.0"

**Comment by 1999** [comment]
@vlaad360 can you please double check if that's still an issue on mocha-parallel-tests@2.0.0?

**Comment by vlaad360** [comment]
Yea, it's just freezing, and do nothing, even if i choose only one test.

**Comment by 1999** [comment]
@vlaad360 what `mocha-parallel-tests` version did you try? Can you try it with the latest one (2.0.0)?

**Comment by 1999** [comment]
Okies, I will try to reproduce your issue in a separate repo.

**Comment by vlaad360** [comment]
1. Part of my **package.json**
```json
"scripts": {
    "test": "SERVER_PORT=8887 DEBUG_PORT=9998 CHOICES_FILE='./src/json/Settings/choises.json' NODE_ENV=test mocha-parallel-tests --opts './mocha.opts'",
}
```
**mocha.opts**
```bash
--require src/js/testHelper.js
--require jsdom-global/register
--require chai/register-expect
--require ts-node/register
--exit
./src/ts/Specs/Detector/Detector.spec.ts
```
2. Stack Trace after lauching
```
mac194rds:Anti-AdBlock v.yandimirkin$ time yarn test
yarn run v1.6.0
$ SERVER_PORT=8887 DEBUG_PORT=9998 CHOICES_FILE='./src/json/Settings/choises.json' NODE_ENV=test mocha-parallel-tests --opts './mocha.opts'


^C

real    1m15.844s
user    0m0.416s
sys     0m0.082s
```

Test is only one file, that include 20 scenarios.

**Comment by vlaad360** [comment]
If i remove --require src/js/testHelper.js
```
mac194rds:Anti-AdBlock v.yandimirkin$ yarn test
yarn run v1.6.0
$ SERVER_PORT=8887 DEBUG_PORT=9998 CHOICES_FILE='./src/json/Settings/choises.json' NODE_ENV=test mocha-parallel-tests --opts './mocha.opts'


Unhaldled asynchronous exception: AssertionError [ERR_ASSERTION]: Subprocess ./src/ts/Specs/Client/Client.spec.ts{undefined} didn't send an "end" message
    at MochaWrapper.findRootData (/Users/v.yandimirkin/Projects/Anti-AdBlock/node_modules/mocha-parallel-tests/src/main/mocha.ts:125:5)
    at MochaWrapper.addSubprocessSuites (/Users/v.yandimirkin/Projects/Anti-AdBlock/node_modules/mocha-parallel-tests/src/main/mocha.ts:135:29)
    at taskManager.run.then (/Users/v.yandimirkin/Projects/Anti-AdBlock/node_modules/mocha-parallel-tests/src/main/mocha.ts:101:14)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 1999** [comment]
Ah, that's better. This one is fixed in upcoming 2.1.0, I will mention you whenever it's published.

**Comment by 1999** [comment]
@vlaad360 this is fixed in the latest (2.0.2) version. Can you try it and say if it helps?

**Comment by vlaad360** [comment]
It works well, but 
Every test add more tabs)

![2018-06-08_12-52-10](https://user-images.githubusercontent.com/8202751/41151936-e50d6844-6b1a-11e8-86c7-39172dc942e6.png)

**Comment by 1999** [comment]
Ah, that's pretty expected: each test is executed in a separate process and their results get merged in the top level suite at the end. That's the main difference from mocha reporting 🤷‍♂️ 
Glad I helped.
