### ISSUE TITLE
"Unhaldled asynchronous exception: Couldn't find test or hook by id" after test retry

### ISSUE THREAD

**Issue by k03mad** [yandex/mocha-parallel-tests#143]
"mocha": "5.2.0",
"mocha-parallel-tests": "2.0.0"

Catching "unhaldled asynchronous exception" with `--retries` parameter or `this.retries` inside describe after test retry.

> ls tests
`test-01.js`

> cat tests/test-01.js
```js
const assert = require('assert');

describe('1 describe', () => {
    it('1 it', () => {
        console.log(1);
        assert(1 === 2);
    });
});
```

> mocha tests --retries 3
```bash
  1 describe
1
1
1
1
    1) 1 it


  0 passing (16ms)
  1 failing

  1) 1 describe
       1 it:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(1 === 2)

      + expected - actual

      -false
      +true
      
      at Context.it (tests/test-01.js:6:9)
```

> mocha-parallel-tests tests --retries 3
```bash
    1 describe
1
1
1
1
Unhaldled asynchronous exception: AssertionError [ERR_ASSERTION]: Couldn't find test or hook by id: e5296a8a74e1a4c0772593d4b15a82df
    at RunnerMain.emitSubprocessEvents (/Users/kirill-m/git/mpt-test/node_modules/mocha-parallel-tests/dist/main/runner.js:154:25)
    at RunnerMain.emitRestEvents (/Users/kirill-m/git/mpt-test/node_modules/mocha-parallel-tests/dist/main/runner.js:117:18)
    at RunnerMain.setTestResults (/Users/kirill-m/git/mpt-test/node_modules/mocha-parallel-tests/dist/main/runner.js:42:14)
    at taskManager.run.then (/Users/kirill-m/git/mpt-test/node_modules/mocha-parallel-tests/dist/main/mocha.js:77:20)
```

**Comment by 1999** [comment]
🤦‍♂️ right, I added a test which checks that the third run is okay but I forgot to check that all 3 runs failed: https://github.com/yandex/mocha-parallel-tests/tree/master/test/retries

**Comment by jetlv** [comment]
Hello,

I got this following error while using the latest release

```
Unhandled asynchronous exception: AssertionError [ERR_ASSERTION]: Couldn't find test by id: 43ef21352a975b77708fa2456045d2dc

    at RunnerMain.emitSubprocessEvents (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/runner.js:138:25)

    at RunnerMain.reEmitSubprocessEvents (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/runner.js:39:14)

    at TaskManager.taskManager.on (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/mocha.js:76:20)

    at emitOne (events.js:116:13)

    at TaskManager.emit (events.js:211:7)

    at TaskManager.onTaskProcessingFinished (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/task-manager.js:19:18)

    at emitTwo (events.js:126:13)

    at TaskManager.emit (events.js:214:7)

    at TaskManager.startTaskProcessing (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/task-manager.js:44:14)

    at <anonymous>
```

I noticed you fixed a bug that tests contains both --bail and --retires would face the issue. But my command has no --bail options. Only retires and I still get the error. Can you please look into this?

I am running test with following command

mocha-parallel-tests test/*.js --retries 2 --timeout 800000 --max-parallel 5 --slow 1000 --recursive"

Thanks

**Comment by 1999** [comment]
@jetlv hey. Better create a separate issue for this one and also put the tests code there. It would help a lot.

**Comment by jetlv** [comment]
@1999 Hi I created a new issue [here](https://github.com/mocha-parallel/mocha-parallel-tests/issues/194)

thanks
