### ISSUE TITLE
Support for mochawesome reporter is missing

### ISSUE THREAD

**Issue by jain-neeeraj** [yandex/mocha-parallel-tests#156]
Hi,

I am using mochawesome as the reporter and I am getting below exception.

```
"mochawesome" reporter not found
Uncaught exception: Error: invalid reporter "mochawesome"
    at MochaWrapper.Mocha.reporter (C:\git\ac3-api-test\node_modules\mocha\lib\mocha.js:174:13)
    at Object.applyReporter [as default] (C:\git\ac3-api-test\node_modules\mocha-parallel-tests\dist\bin\options\reporter.js:7:11)
    at Object.<anonymous> (C:\git\ac3-api-test\node_modules\mocha-parallel-tests\dist\bin\cli.js:121:19)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
```
Please be informed that mochawesome is one of the most famous reporters for mocha

**Comment by 1999** [comment]
Hi @jain-neeeraj, thank you for posting the issue.

As for mochawesome:

1. `mochawesome` is not one of mocha internal reporters which means you need to add it to your dependencies
2. There was still a bug in mocha-parallel-tests@2.0.0 with `mochawesome` but it's already fixed in master branch. The new version will be released in 2-3 days, I will mention you here.

**Comment by 1999** [comment]
mocha-parallel-tests@2.0.1 has just been published. Follow by advice from above (regarding dependencies) to make it work
